version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: postgres_form
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user_form
      POSTGRES_PASSWORD: tu_password
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
